backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/media"
public_folder: "/img"
collections:
  - name: programs
    label: Programs
    folder: "content/programs"
    format: front-matter
    editor:
      preview: false
    create: true
    fields:
      - { name: title, label: Title }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
