backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/media"
public_folder: "/img"
collections:
  - name: programs
    label: Programs
    label_singular: Post
    folder: "content/programs"
    format: frontmatter
    editor:
      preview: false
    create: true
    fields:
      - { name: title, label: Title }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - { label: "Program location", name: "location", widget: "string" }
      - { label: "Images", name: "images", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: pages
    label: Pages
    label_singular: Page
    folder: "content/pages"
    format: frontmatter
    delete: false
    editor:
      preview: false
    create: false
    fields:
      - { name: title, label: Title }
      - { name: name, label: name }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: gallery
        label: Gallery
        file: "content/gallery.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: Images
            name: images
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: Location, name: "location", widget: "string" }
          - label: Videos
            name: videos
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Host", name: "host", widget: "string" }
      - name: "what-we-do"
        label: "What we do"
        file: "content/what-we-do.json"
        fields:
          - label: Activities
            name: activities
            widget: list
            fields:
              - { label: Title, name: title }
              - { label: Icon, name: icon }
              - { label: Description, name: description }
      - name: "programs-list"
        label: "Programs List"
        file: "content/programs-list.md"
        fields:
          - { name: title, label: Title }
          - { name: description, label: Description }
